### ISSUE TITLE
 生成的sing-box配置文件有问题

### ISSUE THREAD

**Issue by jmmail** [cmliu/WARP2sub#1]
生成的sing-box配置文件中

```json 
    {
      "type": "wireguard",
      "tag": "WARP优选IP",
      "inet4_bind_address": "172.16.0.2",
      "local_address": [
        "172.16.0.2/32"
      ],
      "private_key": "",
      "peers": [
        {
          "server": "188.114.96.96",
          "server_port": 946,
          "public_key": "",
          "allowed_ips": [
            "0.0.0.0/0",
            "::/0"
          ]
        }
      ],
      "mtu": 1280,
      "tcp_fast_open": false
    },
```
不应该加入`inet4_bind_address`字段，这个设置与`inbouds`设置中的`tun`入站中的本地IP地址冲突，删除`inet4_bind_address`字段后工作正常。请修改模板文件。

**Comment by cmliu** [comment]
> 生成的sing-box配置文件中
> 
> ```json
>     {
>       "type": "wireguard",
>       "tag": "WARP优选IP",
>       "inet4_bind_address": "172.16.0.2",
>       "local_address": [
>         "172.16.0.2/32"
>       ],
>       "private_key": "",
>       "peers": [
>         {
>           "server": "188.114.96.96",
>           "server_port": 946,
>           "public_key": "",
>           "allowed_ips": [
>             "0.0.0.0/0",
>             "::/0"
>           ]
>         }
>       ],
>       "mtu": 1280,
>       "tcp_fast_open": false
>     },
> ```
> 
> 不应该加入`inet4_bind_address`字段，这个设置与`inbouds`设置中的`tun`入站中的本地IP地址冲突，删除`inet4_bind_address`字段后工作正常。请修改模板文件。

订阅转换是由后端负责的，这个我无能为力
